# PostgreSQL. Versions 10.0+ are supported.
#   Install the pg gem: gem "pg", "~> 1.1"
#   Ensure the pg gem is defined in your Gemfile

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: storage_development

test:
  <<: *default
  database: storage_test

production:
  primary:
    <<: *default
    database: storage_production_primary
  cache:
    <<: *default
    database: storage_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: storage_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: storage_production_cable
    migrations_paths: db/cable_migrate
